---
title: "p8105_hw5_wm2460"
author: "Wenyan Ma"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

## Problem 2
```{r raw}
homicides_df = read_csv("./data/homicide-data.csv")
```

#### Describe the raw data

In the `homicides_df` dataset, there are `r nrow(homicides_df)` observations and `r ncol(homicides_df)` variables. The variables in this dataset include `r colnames(homicides_df)`. 

```{r summarize}
homicides_new = homicides_df %>% 
  janitor::clean_names() %>% 
  mutate(city_state = str_c(city, state, sep = "_"),
         status = 
           case_when(disposition == "Closed without arrest" ~ "unsolved",
                     disposition == "Open/No arrest" ~ "unsolved",
                     disposition == "Closed by arrest" ~ "resolved")) 

summarize_df = homicides_new %>% 
  group_by(city_state) %>% 
  summarize(total = n(),
            unsolved = sum(status == "unsolved")) 

summarize_df
```

#### Using `prop.test` for Baltimore, MD
```{r baltimore}
prop.test(summarize_df %>% filter(city_state == "Baltimore_MD") %>%
            pull(unsolved), 
          summarize_df %>% filter(city_state == "Baltimore_MD") %>%
            pull(total)) %>% 
  broom::tidy()

# save the output of prop.test as an R object
prop.test(summarize_df %>% filter(city_state == "Baltimore_MD") %>%
            pull(unsolved), 
          summarize_df %>% filter(city_state == "Baltimore_MD") %>%
            pull(total)) %>% 
  broom::tidy() %>% 
  saveRDS(., "./data/Baltimore_prop_test.rds")
```

#### Using `prop.test` for each cities
```{r all_cities}
all_cities = summarize_df %>% 
  mutate(prop_tests = map2(.x = unsolved, .y = total, ~ prop.test(x = .x, n = .y)),
         tidy_df = map(.x = prop_tests, ~ broom::tidy(.x))) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_df) %>% 
  select(city_state, estimate, conf.low, conf.high)

all_cities
```

#### A plot that shows the estimates and CIs for each city 
```{r plot}
all_cities_plot = all_cities %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

all_cities_plot
```


## Problem 3

#### Set up the simulation
```{r simulation}
sim_p3 = function(n = 30, mu = 0, sigma = 5) {
     x = rnorm(n, mean = mu, sd = sigma)
     t_test = t.test(x, conf.int = 0.95) %>% broom::tidy()
     
     t_test
}

p3_df = vector("list", 1000)

for (i in 1:1000) {
  p3_df[[i]] = sim_p3()
}

p3_df %>% 
  bind_rows() %>% 
  head()
```








